// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:524396819463:web:96af1acc4c1b0cadf826a2',
    messagingSenderId: '524396819463',
    projectId: 'crudonlinedb-8e05b',
    authDomain: 'crudonlinedb-8e05b.firebaseapp.com',
    storageBucket: 'crudonlinedb-8e05b.firebasestorage.app',
    measurementId: 'G-9Q619K9W4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:524396819463:android:fa6c43dc64aba83af826a2',
    messagingSenderId: '524396819463',
    projectId: 'crudonlinedb-8e05b',
    storageBucket: 'crudonlinedb-8e05b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:524396819463:ios:746274e677d0cab5f826a2',
    messagingSenderId: '524396819463',
    projectId: 'crudonlinedb-8e05b',
    storageBucket: 'crudonlinedb-8e05b.firebasestorage.app',
    iosBundleId: 'com.example.crudonlinedb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "your key",
    appId: '1:524396819463:ios:746274e677d0cab5f826a2',
    messagingSenderId: '524396819463',
    projectId: 'crudonlinedb-8e05b',
    storageBucket: 'crudonlinedb-8e05b.firebasestorage.app',
    iosBundleId: 'com.example.crudonlinedb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:524396819463:web:d2d9e9631c5c584bf826a2',
    messagingSenderId: '524396819463',
    projectId: 'crudonlinedb-8e05b',
    authDomain: 'crudonlinedb-8e05b.firebaseapp.com',
    storageBucket: 'crudonlinedb-8e05b.firebasestorage.app',
    measurementId: 'G-L9LMR915QX',
  );
}
